//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPSIGestionSoftSony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipement()
        {
            this.panneequipement = new HashSet<panneequipement>();
        }
    
        public string NumSerie { get; set; }
        public string Machine { get; set; }
        public string Description { get; set; }
        public string Application { get; set; }
        public string Ip { get; set; }
        public Nullable<int> Ram { get; set; }
        public string Categorie { get; set; }
        public string Modele { get; set; }
        public System.DateTime Dt_achat { get; set; }
        public string IMMO { get; set; }
        public string WinProdKey { get; set; }
        public string System { get; set; }
        public string Etat { get; set; }
        public Nullable<System.DateTime> Dt_sortie { get; set; }
        public string SSID1 { get; set; }
        public string SSID2 { get; set; }
        public string Garantie { get; set; }
        public Nullable<int> poste_Id { get; set; }
        public string Marque { get; set; }
    
        public virtual poste poste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<panneequipement> panneequipement { get; set; }
    }
}
