//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPSIGestionSoftSony.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionParcContext : DbContext
    {
        public GestionParcContext()
            : base("name=GestionParcContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<atelier> atelier { get; set; }
        public virtual DbSet<equipement> equipement { get; set; }
        public virtual DbSet<hdd> hdd { get; set; }
        public virtual DbSet<historiquepanneequipement> historiquepanneequipement { get; set; }
        public virtual DbSet<historiquepannehdd> historiquepannehdd { get; set; }
        public virtual DbSet<ligne> ligne { get; set; }
        public virtual DbSet<panne> panne { get; set; }
        public virtual DbSet<panneequipement> panneequipement { get; set; }
        public virtual DbSet<pannehdd> pannehdd { get; set; }
        public virtual DbSet<poste> poste { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
        public virtual DbSet<backup> backup { get; set; }
    }
}
